version: '3'
services:
    node:
        image: node:12.14.1
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - "3000:3000"
        tty: true
